// 📦 مكتبة التمارين التفاعلية – قابلة لإعادة الاستخدام

const exercises = [
  // ── التمارين الأصلية ────────────────────────────
  {
    id: 'ex-001',
    section: 'الزوايا',
    sectionIcon: '📐',
    name: 'تسمية الزاوية',
    description: 'تمرين تفاعلي لتعلّم تسمية الزوايا باستخدام الرأس والضلعين. 10 محاولات مع نقاط.',
    difficulty: 'easy',
    class: 'السابعة أساسي',
    cardColor: '#e06c2e',
    cardColorDark: '#f08a50',
    link: 'تمرين الزاوية.html',
    version: '1.1',
    tags: ['زوايا', 'تسمية', 'هندسة', 'رأس الزاوية'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-01-15',
    estimatedTime: '5-8 دقائق',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['زاوية', 'ضلع', 'رأس', 'تسمية الزاوية', 'BAC'],
    thumbnail: '📐',
  },
  {
    id: 'ex-002',
    section: 'تقايس المثلثات',
    sectionIcon: '🔺',
    name: 'تقايس المثلثات – الحالة الثانية (ASA)',
    description: 'تمرين حول تقايس مثلثين حسب حالة زاوية-ضلع-زاوية. 10 فراغات للإكمال مع رسم تفاعلي.',
    difficulty: 'medium',
    class: 'الثامنة أساسي',
    cardColor: '#2a7db5',
    cardColorDark: '#5ba0d0',
    link: 'تقايس المثلثات – الحالة الثانية.html',
    version: '1.1',
    tags: ['تقايس', 'مثلثات', 'ASA', 'زاوية-ضلع-زاوية', 'هندسة'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-02-20',
    estimatedTime: '8-12 دقيقة',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['تقايس', 'مثلث', 'ASA', 'زاوية', 'ضلع', 'حالة ثانية'],
    thumbnail: '🔺',
  },
  {
    id: 'ex-003',
    section: 'التوازي',
    sectionIcon: '📏',
    name: 'تمرين التوازي – أبعاد مضبوطة',
    description: 'تمرين لتحديد المستقيم الموازي والقاطع من رسم توضيحي. 10 محاولات مع نقاط.',
    difficulty: 'easy',
    class: 'السابعة أساسي',
    cardColor: '#1f8a4c',
    cardColorDark: '#4ade80',
    link: 'تمرين التوازي.html',
    version: '1.1',
    tags: ['توازي', 'مستقيمات', 'قاطع', 'هندسة'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-03-10',
    estimatedTime: '4-7 دقائق',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['توازي', 'مستقيم', 'قاطع', 'موازي'],
    thumbnail: '📏',
  },

  {
    id: 'ex-004',
    section: 'الزوايا',
    sectionIcon: '📐',
    name: 'الزوايا الداخلية من نفس الجهة',
    description: 'تمرين تفاعلي حول الزوايا الداخلية من نفس الجهة. يدعم العربية والفرنسية والإنجليزية، مع صوت ووضع ليلي. 10 محاولات مع نقاط.',
    difficulty: 'medium',
    class: 'السابعة أساسي',
    cardColor: '#2c6e9e',
    cardColorDark: '#5ba0d0',
    link: 'الزوايا الداخلية من نفس الجهة.html',
    version: '1.1',
    tags: ['زوايا', 'داخلية', 'نفس الجهة', 'متوازيان', 'قاطع', 'هندسة'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-04-25',
    estimatedTime: '5-8 دقائق',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['زوايا داخلية', 'متكاملتان', 'قاطع', 'موازي', 'نفس الجهة'],
    thumbnail: '📐',
  },
  {
    id: 'ex-005',
    section: 'الزوايا',
    sectionIcon: '📐',
    name: 'الزوايا المتبادلة داخلياً',
    description: 'تمرين تفاعلي حول الزوايا المتبادلة داخلياً. يدعم العربية والفرنسية والإنجليزية، مع صوت ووضع ليلي. 10 محاولات مع نقاط.',
    difficulty: 'medium',
    class: 'السابعة أساسي',
    cardColor: '#b34130',
    cardColorDark: '#e07060',
    link: 'الزوايا المتبادلة داخلياً.html',
    version: '1.1',
    tags: ['زوايا', 'متبادلة', 'داخلياً', 'متوازيان', 'قاطع', 'هندسة'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-04-25',
    estimatedTime: '5-8 دقائق',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['زوايا متبادلة', 'تقايس', 'قاطع', 'موازي'],
    thumbnail: '📐',
  },
  {
    id: 'ex-006',
    section: 'الزوايا',
    sectionIcon: '📐',
    name: 'الزوايا المتقابلة بالرأس',
    description: 'تمرين تفاعلي حول الزوايا المتقابلة بالرأس عند تقاطع مستقيمين متوازيين مع قاطع. يدعم العربية والفرنسية والإنجليزية، مع صوت ووضع ليلي. 10 محاولات مع نقاط.',
    difficulty: 'medium',
    class: 'السابعة أساسي',
    cardColor: '#8a3b7c',
    cardColorDark: '#c060b0',
    link: 'الزوايا المتقابلة بالرأس.html',
    version: '1.1',
    tags: ['زوايا', 'متقابلة بالرأس', 'هندسة', 'قاطع', 'متوازيان'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-04-25',
    estimatedTime: '5-8 دقائق',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['متقابلة بالرأس', 'تقايس', 'قاطع', 'موازي'],
    thumbnail: '📐',
  },
  {
    id: 'ex-007',
    section: 'تقايس المثلثات',
    sectionIcon: '🔺',
    name: 'تقايس المثلثات – الحالة الأولى (AAA)',
    description: 'تمرين تفاعلي حول تقايس المثلثات حسب الحالة الأولى (زاوية-زاوية-زاوية) مع رسم مثلثين متقايسين وأقواس ملوّنة. يدعم العربية والفرنسية والإنجليزية، مع صوت ووضع ليلي. 10 محاولات مع نقاط.',
    difficulty: 'hard',
    class: 'الثامنة أساسي',
    cardColor: '#d9443a',
    cardColorDark: '#f07060',
    link: 'تقايس المثلثات – الحالة الأولى.html',
    version: '1.1',
    tags: ['تقايس', 'مثلثات', 'AAA', 'زاوية-زاوية-زاوية', 'هندسة'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-04-25',
    estimatedTime: '10-15 دقيقة',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['تقايس', 'مثلث', 'AAA', 'زاوية', 'حالة أولى'],
    thumbnail: '🔺',
  },
  {
    id: 'ex-008',
    section: 'تقايس المثلثات',
    sectionIcon: '🔺',
    name: 'تقايس المثلثات – الحالة الثالثة (SAS)',
    description: 'تمرين تفاعلي حول تقايس المثلثات حسب الحالة الثالثة (ضلع-زاوية-ضلع). 10 محاولات مع رسم مثلثين.',
    difficulty: 'hard',
    class: 'الثامنة أساسي',
    cardColor: '#2e7d32',
    cardColorDark: '#4caf50',
    link: 'تقايس المثلثات – الحالة الثالثة.html',
    version: '1.1',
    tags: ['تقايس', 'مثلثات', 'SAS', 'ضلع-زاوية-ضلع', 'هندسة'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-04-25',
    estimatedTime: '10-15 دقيقة',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['تقايس', 'مثلث', 'SAS', 'ضلع', 'زاوية', 'حالة ثالثة'],
    thumbnail: '🔺',
  },
    {
    id: 'ex-009',
    section: 'تقايس المثلثات',
    sectionIcon: '📐🔺',
    name: 'تقايس المثلثات القائمة – الحالة الأولى (HA)',
    description: 'تمرين تفاعلي حول تقايس المثلثات القائمة حسب الحالة الأولى (الوتر وزاوية حادة). 10 محاولات مع نقاط، يدعم العربية والفرنسية والإنجليزية.',
    difficulty: 'medium',
    class: 'الثامنة أساسي',
    cardColor: '#9c27b0',
    cardColorDark: '#ce93d8',
    link: 'تقايس المثلثات القائمة - الحالة الأولى.html',
    version: '1.0',
    tags: ['تقايس', 'مثلثات قائمة', 'الوتر', 'زاوية حادة', 'HA', 'هندسة'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2026-04-26',
    estimatedTime: '6-10 دقائق',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['تقايس', 'مثلث قائم', 'حالة أولى', 'الوتر', 'زاوية حادة', 'HA'],
    thumbnail: '📐',
  },
    {
    id: 'ex-010',
    section: 'تقايس المثلثات',
    sectionIcon: '🔺',
    name: 'تقايس المثلثات القائمة – الحالة الثانية',
    description: 'تمرين تفاعلي حول تقايس المثلثات القائمة حسب الحالة الثانية (الوتر وضلع قائم – HL). 10 محاولات مع رسم مثلثين.',
    difficulty: 'hard',
    class: 'الثامنة أساسي',
    cardColor: '#b34130',
    cardColorDark: '#f87171',
    link: 'تقايس المثلثات القائمة - الحالة الثانية.html',
    version: '1.0',
    tags: ['تقايس', 'مثلثات قائمة', 'HL', 'الوتر', 'ضلع قائم', 'هندسة'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-04-26',
    estimatedTime: '10-15 دقيقة',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['تقايس', 'مثلث قائم', 'HL', 'الوتر', 'ضلع قائم', 'حالة ثانية'],
    thumbnail: '🔺',
  },
    {
    id: 'ex-011',
    section: 'الإحصاء',
    sectionIcon: '📊',
    name: 'المدى',
    description: 'تمرين تفاعلي حول إيجاد المدى (أكبر قيمة – أصغر قيمة) من مجموعة أعداد. 10 محاولات مع نقاط.',
    difficulty: 'easy',
    class: 'السابعة أساسي',
    cardColor: '#8b5cf6',
    cardColorDark: '#a78bfa',
    link: 'الاحصاء - المدى.html',
    version: '1.0',
    tags: ['إحصاء', 'مدى', 'قيم', 'أعداد'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-04-26',
    estimatedTime: '4-6 دقائق',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['مدى', 'قيمة كبرى', 'قيمة صغرى', 'إحصاء', 'أعداد'],
    thumbnail: '📊',
  },
    {
    id: 'ex-012',
    section: 'الإحصاء',
    sectionIcon: '📊',
    name: 'الوسط الحسابي (المتوسط)',
    description: 'تمرين تفاعلي لحساب الوسط الحسابي من مجموعة بيانات مع جدول قيم ومدخلات. 10 محاولات مع نقاط.',
    difficulty: 'easy',
    class: 'السابعة أساسي',
    cardColor: '#6366f1',
    cardColorDark: '#818cf8',
    link: 'الاحصاء - الوسط الحسابي.html',
    version: '1.0',
    tags: ['إحصاء', 'وسط', 'متوسط', 'حساب', 'جدول'],
    mainLanguage: 'العربية',
    availableTranslations: ['العربية', 'Français', 'English'],
    author: 'فريق الرياضيات',
    dateAdded: '2025-04-26',
    estimatedTime: '5-8 دقائق',
    questionCount: 10,
    curriculum: 'المرحلة الإعدادية',
    keywords: ['وسط حسابي', 'مجموع', 'عدد', 'متوسط', 'إحصاء'],
    thumbnail: '📊',
  }
];

// تصدير للمتصفح (للاستخدام داخل الوسم <script>)
if (typeof window !== 'undefined') {
  window.exercises = exercises;
}